// AUTO-GENERATED by tests/fixtures/map-blocked/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

const WALKER = {
  idle: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkL: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkR: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
};

export const GAME_ASSETS: GameAssets = {
  ground: {
    "map-blocked-a": ["assets/map-map-blocked-a-ground.png"],
    "map-blocked-b": ["assets/map-map-blocked-b-ground.png"],
  },
  upper: {
    "map-blocked-a": ["assets/map-map-blocked-a-upper.png"],
    "map-blocked-b": ["assets/map-map-blocked-b-upper.png"],
  },
  chunkColumns: { "map-blocked-a": 1, "map-blocked-b": 1 },
  maxChunks: 1,
  maxActors: 4,
  world: {
    "map-blocked-a": { w: 64, h: 64 },
    "map-blocked-b": { w: 64, h: 64 },
  },
  order: ["map-blocked-a", "map-blocked-b"],
  npcSrc: {},
  player: WALKER,
};
