// tests/fixtures/map-blocked/gen-assets.ts — procedural art for the
// map-blocked fixture: two trivial 4x4 maps plus a placeholder walker so
// GameView's actor mount has art. Reproducible byte for byte; the PNGs are
// build outputs kept out of git.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import { bakeMapChunks, groundChunkAsset, upperChunkAsset } from "../../../tools/lib/chunks.ts";
import { CHUNK_PX, TILE } from "../../../src/engine/tiles.ts";
import { MAPS } from "./fixture-data.ts";

const HERE = import.meta.dir;
const ASSETS = join(HERE, "assets");
mkdirSync(ASSETS, { recursive: true });

type Rgba = readonly [number, number, number, number];

function solidTile(colour: Rgba): Uint8Array {
  const out = new Uint8Array(TILE * TILE * 4);
  for (let i = 0; i < TILE * TILE; i++) out.set(colour, i * 4);
  return out;
}

function solidImage(colour: Rgba, size: number): Uint8Array {
  const out = new Uint8Array(size * size * 4);
  for (let i = 0; i < size * size; i++) out.set(colour, i * 4);
  return out;
}

const ground = solidTile([18, 26, 20, 255]);
for (const map of MAPS) {
  const baked = bakeMapChunks(map, () => ground, ground);
  const chunkCount = baked.columns * baked.rows;
  for (let i = 0; i < chunkCount; i++) {
    writeFileSync(join(HERE, groundChunkAsset(map.id, i, chunkCount)), encodePNG(baked.ground[i]!, CHUNK_PX, CHUNK_PX));
    writeFileSync(join(HERE, upperChunkAsset(map.id, i, chunkCount)), encodePNG(baked.upper[i]!, CHUNK_PX, CHUNK_PX));
  }
}

writeFileSync(join(HERE, "assets/walker.png"), encodePNG(solidImage([80, 80, 96, 255], TILE), TILE, TILE));

const q = (id: string): string => JSON.stringify(id);
const frames = '["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"]';
writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/map-blocked/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

const WALKER = {
  idle: ${frames} as const,
  walkL: ${frames} as const,
  walkR: ${frames} as const,
};

export const GAME_ASSETS: GameAssets = {
  ground: {
    ${q(MAPS[0]!.id)}: ["assets/map-${MAPS[0]!.id}-ground.png"],
    ${q(MAPS[1]!.id)}: ["assets/map-${MAPS[1]!.id}-ground.png"],
  },
  upper: {
    ${q(MAPS[0]!.id)}: ["assets/map-${MAPS[0]!.id}-upper.png"],
    ${q(MAPS[1]!.id)}: ["assets/map-${MAPS[1]!.id}-upper.png"],
  },
  chunkColumns: { ${q(MAPS[0]!.id)}: 1, ${q(MAPS[1]!.id)}: 1 },
  maxChunks: 1,
  maxActors: 4,
  world: {
    ${q(MAPS[0]!.id)}: { w: ${MAPS[0]!.width * TILE}, h: ${MAPS[0]!.height * TILE} },
    ${q(MAPS[1]!.id)}: { w: ${MAPS[1]!.width * TILE}, h: ${MAPS[1]!.height * TILE} },
  },
  order: [${q(MAPS[0]!.id)}, ${q(MAPS[1]!.id)}],
  npcSrc: {},
  player: WALKER,
};
`,
);
