// AUTO-GENERATED by tests/fixtures/text-tokens/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

const WALKER = {
  idle: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkL: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkR: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
};

export const GAME_ASSETS: GameAssets = {
  ground: { "text-tokens-field": ["assets/map-text-tokens-field-ground.png"] },
  upper: { "text-tokens-field": ["assets/map-text-tokens-field-upper.png"] },
  chunkColumns: { "text-tokens-field": 1 },
  maxChunks: 1,
  world: { "text-tokens-field": { w: 64, h: 64 } },
  order: ["text-tokens-field"],
  npcSrc: {},
  player: WALKER,
};
