// AUTO-GENERATED by examples/sunstone/gen-assets.ts — GameView asset
// literals (full strings so tools/build.ts bakes them) and per-map world
// geometry. Every map owns row-major 512px chunk image lists.

import type { GameAssets } from "../../src/ui/game-assets.ts";

export const MAP_CANVAS_PX = 512;

export const MAP_GROUND: Record<string, readonly string[]> = {
  "village": ["assets/map-village-ground.png"],
  "forest": ["assets/map-forest-ground.png"],
  "cave": ["assets/map-cave-ground.png"],
};

export const MAP_UPPER: Record<string, readonly string[]> = {
  "village": ["assets/map-village-upper.png"],
  "forest": ["assets/map-forest-upper.png"],
  "cave": ["assets/map-cave-upper.png"],
};

export const MAP_CHUNK_COLUMNS: Record<string, number> = {
  "village": 1,
  "forest": 1,
  "cave": 1,
};

export const MAP_MAX_CHUNKS = 1;

export const MAP_WORLD: Record<string, { w: number; h: number }> = {
  "village": { w: 320, h: 208 },
  "forest": { w: 288, h: 224 },
  "cave": { w: 288, h: 208 },
};

export const MAP_ORDER: readonly string[] = ["village","forest","cave"];

export const NPC_SRC: Record<string, string> = {
  "wiz": "assets/npc/wiz.png",
  "boy": "assets/npc/boy.png",
  "merchant": "assets/npc/merchant.png",
  "villager": "assets/npc/villager.png",
  "slime": "assets/npc/slime.png",
  "bat": "assets/npc/bat.png",
  "chest-closed": "assets/npc/chest-a.png",
  "chest-open": "assets/npc/chest-b.png",
  "chest-relic": "assets/npc/chest-c.png",
  "thorn": "assets/npc/thorn.png",
  "irongate": "assets/npc/irongate.png",
  "runestone": "assets/npc/runestone.png",
  "runestone-lit": "assets/npc/runestone-lit.png",
};

// Player walker frames, facing order 0 down, 1 left, 2 up, 3 right.
export const PLAYER_IDLE: readonly [string, string, string, string] = [
  "assets/player-dir0.png",
  "assets/player-dir1.png",
  "assets/player-dir2.png",
  "assets/player-dir3.png",
];

export const PLAYER_WALK_L: readonly [string, string, string, string] = [
  "assets/player-pose0-l.png",
  "assets/player-pose1-l.png",
  "assets/player-pose2-l.png",
  "assets/player-pose3-l.png",
];

export const PLAYER_WALK_R: readonly [string, string, string, string] = [
  "assets/player-pose0-r.png",
  "assets/player-pose1-r.png",
  "assets/player-pose2-r.png",
  "assets/player-pose3-r.png",
];

export const GAME_ASSETS: GameAssets = {
  ground: MAP_GROUND,
  upper: MAP_UPPER,
  chunkColumns: MAP_CHUNK_COLUMNS,
  maxChunks: MAP_MAX_CHUNKS,
  maxActors: 9,
  world: MAP_WORLD,
  order: MAP_ORDER,
  npcSrc: NPC_SRC,
  player: { idle: PLAYER_IDLE, walkL: PLAYER_WALK_L, walkR: PLAYER_WALK_R },
};
