// AUTO-GENERATED by tests/fixtures/kb4-battle/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

const WALKER = {
  idle: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkL: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkR: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
};

export const GAME_ASSETS: GameAssets = {
  ground: { "kb4-field": ["assets/map-kb4-field-ground.png"] },
  upper: { "kb4-field": ["assets/map-kb4-field-upper.png"] },
  chunkColumns: { "kb4-field": 1 },
  maxChunks: 1,
  world: { "kb4-field": { w: 64, h: 64 } },
  order: ["kb4-field"],
  npcSrc: {},
  player: WALKER,
};

/** Battle-scene-only art (src/ui/battle demo): not part of GameAssets. */
export const KB4_ART = {
  player: {"kind":"tile","ref":"ui:tile.kb4-battle/player#0","sourceWidth":64,"sourceHeight":64},
  enemy: {"kind":"tile","ref":"ui:tile.kb4-battle/enemy#0","sourceWidth":64,"sourceHeight":64},
} as const;
