// tests/fixtures/kb4-battle/gen-assets.ts — procedural art for the KB4
// demo fixture: a trivial 4x4 map (never actually walked; battle starts on
// map entry) plus two small battler portraits so SpriteSlot has something
// visible to shake/sink. Reproducible byte for byte; the PNGs are build
// outputs kept out of git (.gitignore, matching every other fixture).

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import { bakeMapChunks, groundChunkAsset, upperChunkAsset } from "../../../tools/lib/chunks.ts";
import { encodeClut8Tile } from "../../../tools/lib/clut8.ts";
import { CHUNK_PX, TILE } from "../../../src/engine/tiles.ts";
import { MAP, MAP_ID, MAP_SIZE } from "./fixture-data.ts";

const HERE = import.meta.dir;
const ASSETS = join(HERE, "assets");
mkdirSync(ASSETS, { recursive: true });

type Rgba = readonly [number, number, number, number];

function solidTile(colour: Rgba): Uint8Array {
  const out = new Uint8Array(TILE * TILE * 4);
  for (let i = 0; i < TILE * TILE; i++) out.set(colour, i * 4);
  return out;
}

function solidImage(colour: Rgba, size: number): Uint8Array {
  const out = new Uint8Array(size * size * 4);
  for (let i = 0; i < size * size; i++) out.set(colour, i * 4);
  return out;
}

const ground = solidTile([18, 26, 20, 255]);
const baked = bakeMapChunks(MAP, () => ground, ground);
const chunkCount = baked.columns * baked.rows;
for (let i = 0; i < chunkCount; i++) {
  writeFileSync(join(HERE, groundChunkAsset(MAP_ID, i, chunkCount)), encodePNG(baked.ground[i]!, CHUNK_PX, CHUNK_PX));
  writeFileSync(join(HERE, upperChunkAsset(MAP_ID, i, chunkCount)), encodePNG(baked.upper[i]!, CHUNK_PX, CHUNK_PX));
}

// One placeholder walker frame reused for all 12 pose/facing slots: the
// map is never actually walked on (battle starts the instant the session
// boots), so only its existence matters for GameView's actor mount.
const walkerName = "assets/walker.png";
writeFileSync(join(HERE, walkerName), encodePNG(solidImage([80, 80, 96, 255], TILE), TILE, TILE));

// Battler portraits: distinct flat colours with a simple face mark so a
// screenshot still reads as "two different sprites" at a glance.
// Pak images must be power-of-two edges (framework/compiler/pak.ts).
const SPRITE_SIZE = 64;
function battler(body: Rgba, mark: Rgba): Uint8Array {
  const out = solidImage(body, SPRITE_SIZE);
  for (let y = 20; y < 28; y++) {
    for (let x = 16; x < 48; x++) out.set(mark, (y * SPRITE_SIZE + x) * 4);
  }
  return out;
}
const playerName = "assets/battler-player.png";
const enemyName = "assets/battler-enemy.png";
const playerRgba = battler([214, 90, 74, 255], [20, 12, 10, 255]);
const enemyRgba = battler([74, 150, 214, 255], [10, 16, 20, 255]);
writeFileSync(join(HERE, playerName), encodePNG(playerRgba, SPRITE_SIZE, SPRITE_SIZE));
writeFileSync(join(HERE, enemyName), encodePNG(enemyRgba, SPRITE_SIZE, SPRITE_SIZE));
const playerTile = encodeClut8Tile("kb4-battle/player", {
  width: SPRITE_SIZE, height: SPRITE_SIZE, rgba: playerRgba,
});
const enemyTile = encodeClut8Tile("kb4-battle/enemy", {
  width: SPRITE_SIZE, height: SPRITE_SIZE, rgba: enemyRgba,
});
const playerTileFile = "assets/battler-player.pkts";
const enemyTileFile = "assets/battler-enemy.pkts";
writeFileSync(join(HERE, playerTileFile), playerTile.blob);
writeFileSync(join(HERE, enemyTileFile), enemyTile.blob);
writeFileSync(join(HERE, "pak.json"), JSON.stringify([
  { key: enemyTile.key, file: enemyTileFile },
  { key: playerTile.key, file: playerTileFile },
], null, 2) + "\n");

const groundNames = Array.from({ length: chunkCount }, (_, i) => groundChunkAsset(MAP_ID, i, chunkCount));
const upperNames = Array.from({ length: chunkCount }, (_, i) => upperChunkAsset(MAP_ID, i, chunkCount));
const q = JSON.stringify;
const names = (values: readonly string[]): string => `[${values.map((v) => q(v)).join(", ")}]`;

writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/kb4-battle/gen-assets.ts — do not edit.\n` +
    `import type { GameAssets } from "../../../src/ui/game-assets.ts";\n\n` +
    `const WALKER = {\n` +
    `  idle: ${names([walkerName, walkerName, walkerName, walkerName])} as const,\n` +
    `  walkL: ${names([walkerName, walkerName, walkerName, walkerName])} as const,\n` +
    `  walkR: ${names([walkerName, walkerName, walkerName, walkerName])} as const,\n` +
    `};\n\n` +
    `export const GAME_ASSETS: GameAssets = {\n` +
    `  ground: { ${q(MAP_ID)}: ${names(groundNames)} },\n` +
    `  upper: { ${q(MAP_ID)}: ${names(upperNames)} },\n` +
    `  chunkColumns: { ${q(MAP_ID)}: ${baked.columns} },\n` +
    `  maxChunks: ${chunkCount},\n` +
    `  world: { ${q(MAP_ID)}: { w: ${MAP_SIZE.width * TILE}, h: ${MAP_SIZE.height * TILE} } },\n` +
    `  order: [${q(MAP_ID)}],\n` +
    `  npcSrc: {},\n` +
    `  player: WALKER,\n` +
    `};\n\n` +
    `/** Battle-scene-only art (src/ui/battle demo): not part of GameAssets. */\n` +
    `export const KB4_ART = {\n` +
    `  player: ${JSON.stringify(playerTile.descriptor)},\n` +
    `  enemy: ${JSON.stringify(enemyTile.descriptor)},\n` +
    `} as const;\n`,
);

console.log(`kb4-battle fixture: ${MAP_SIZE.width}x${MAP_SIZE.height} map, 1 ground/upper chunk, 2 lazy CLUT8 battler portraits`);
