// Deterministically cook five placed maps and two legacy-fallback maps into
// streamed TILESET entries plus the player and two one-frame animated
// terrain atlases.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import {
  encodeStreamedLayer,
  pakManifest,
  streamEntryFile,
  streamManifestSource,
  type StreamEntry,
  type StreamedLayer,
} from "../../../tools/lib/stream.ts";
import {
  ABOVE_ANIM_COLOUR,
  ANIMATED,
  BELOW_ANIM_COLOUR,
  MAPS,
  PLAYER_COLOUR,
  PLAYER_OUTLINE,
  type Rgba,
} from "./fixture-data.ts";

const HERE = import.meta.dir;
const TILE = 16;
const CHUNK = 256;

interface CookedMap {
  ground: StreamedLayer;
  upper: StreamedLayer;
}

const upperMarker = new Map<string, readonly [number, number]>([
  ["a-northwest", [63, 39]],
  ["b-northeast", [0, 39]],
  ["c-southwest", [63, 0]],
  ["d-southeast", [0, 0]],
  ["e-small", [1, 4]],
  ["unplaced-field", [63, 39]],
  ["indoor-room", [1, 4]],
]);

function paintChunk(
  map: typeof MAPS[number],
  chunkX: number,
  chunkY: number,
  upper: boolean,
): Uint8Array {
  const rgba = new Uint8Array(CHUNK * CHUNK * 4);
  const marker = upperMarker.get(map.id)!;
  for (let y = 0; y < CHUNK; y++) {
    const mapY = chunkY * CHUNK + y;
    if (mapY >= map.height * TILE) break;
    for (let x = 0; x < CHUNK; x++) {
      const mapX = chunkX * CHUNK + x;
      if (mapX >= map.width * TILE) break;
      let colour: Rgba | undefined;
      if (!upper) {
        colour = map.ground;
      } else {
        const tileX = Math.floor(mapX / TILE);
        const tileY = Math.floor(mapY / TILE);
        const pixelX = mapX % TILE;
        if (tileX === marker[0] && tileY === marker[1]) colour = map.upper;
        // The active player occupies this NW tile. Only its right half is an
        // upper pixel, leaving actor and upper semantic probes side by side.
        if (map.id === "a-northwest" && tileX === 62 && tileY === 38 && pixelX >= 8) {
          colour = map.upper;
        }
      }
      if (colour) rgba.set(colour, (y * CHUNK + x) * 4);
    }
  }
  return rgba;
}

const entries: StreamEntry[] = [];
const cooked = new Map<string, CookedMap>();
for (const map of MAPS) {
  const columns = Math.ceil(map.width * TILE / CHUNK);
  const rows = Math.ceil(map.height * TILE / CHUNK);
  const groundChunks: Uint8Array[] = [];
  const upperChunks: Uint8Array[] = [];
  for (let y = 0; y < rows; y++) {
    for (let x = 0; x < columns; x++) {
      groundChunks.push(paintChunk(map, x, y, false));
      upperChunks.push(paintChunk(map, x, y, true));
    }
  }
  const ground = encodeStreamedLayer(`world-${map.id}-ground`, groundChunks, columns, rows, { chunkPx: CHUNK });
  const upper = encodeStreamedLayer(`world-${map.id}-upper`, upperChunks, columns, rows, { chunkPx: CHUNK });
  entries.push(...ground.entries, ...upper.entries);
  cooked.set(map.id, { ground: ground.layer, upper: upper.layer });
}

for (const entry of entries) {
  const path = join(HERE, streamEntryFile(entry.key));
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.blob);
}
writeFileSync(join(HERE, "pak.json"), JSON.stringify(pakManifest(entries), null, 2) + "\n");

function solidSprite(colour: Rgba, border: Rgba | undefined): Uint8Array {
  const rgba = new Uint8Array(TILE * TILE * 4);
  for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < TILE; x++) {
      const edge = x === 0 || y === 0 || x === TILE - 1 || y === TILE - 1;
      rgba.set(edge && border ? border : colour, (y * TILE + x) * 4);
    }
  }
  return rgba;
}

mkdirSync(join(HERE, "assets", "anim"), { recursive: true });
writeFileSync(join(HERE, "assets", "player.png"), encodePNG(solidSprite(PLAYER_COLOUR, PLAYER_OUTLINE), TILE, TILE));
writeFileSync(join(HERE, "assets", "anim", "below.png"), encodePNG(solidSprite(BELOW_ANIM_COLOUR, undefined), TILE, TILE));
writeFileSync(join(HERE, "assets", "anim", "above.png"), encodePNG(solidSprite(ABOVE_ANIM_COLOUR, undefined), TILE, TILE));
writeFileSync(join(HERE, "images.json"), JSON.stringify({ "assets/player.png": { psm: 3 } }, null, 2) + "\n");
writeFileSync(join(HERE, "sprites.json"), JSON.stringify({
  "assets/anim/below.png": { cols: 1, rows: 1, frames: 1, step: 1, psm: 3 },
  "assets/anim/above.png": { cols: 1, rows: 1, frames: 1, step: 1, psm: 3 },
}, null, 2) + "\n");

const stream = streamManifestSource(MAPS.map((map) => ({
  id: map.id,
  width: map.width,
  height: map.height,
  ground: cooked.get(map.id)!.ground,
  upper: cooked.get(map.id)!.upper,
})), { chunkPx: CHUNK, margin: TILE });
const q = JSON.stringify;
const frames = `[${Array.from({ length: 4 }, () => q("assets/player.png")).join(", ")}]`;
writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/world-streamed/gen-assets.ts — do not edit.\n` +
    `import type { GameAssets } from "../../../src/ui/game-assets.ts";\n` +
    `import { ANIMATED } from "./fixture-data.ts";\n\n` +
    `export const GAME_ASSETS: GameAssets = {\n` +
    `  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 0,\n` +
    `  world: {\n` +
    MAPS.map((map) => `    ${q(map.id)}: { w: ${map.width * TILE}, h: ${map.height * TILE} },`).join("\n") + `\n` +
    `  },\n` +
    `  order: ${JSON.stringify(MAPS.map((map) => map.id))},\n` +
    `  npcSrc: {},\n` +
    `  player: { idle: ${frames}, walkL: ${frames}, walkR: ${frames} },\n` +
    `  stream: ${stream},\n` +
    `  animated: ANIMATED,\n` +
    `};\n`,
);
console.log(
  `world-streamed fixture: ${MAPS.length} maps, ${entries.length} TILESET entries, ` +
  `${entries.reduce((sum, entry) => sum + entry.blob.length, 0)} bytes, ` +
  `${Object.values(ANIMATED).reduce((sum, tiles) => sum + tiles.length, 0)} animated tiles`,
);
