// AUTO-GENERATED by editor/gen-assets.ts — the baked art the editor
// playtest dresses its documents in: item icons, Show Animation frames
// and parallax images (cells and slices of the bundled example sheets).
// Editor-only, like playtest-assets.ts. Do not edit by hand.

import type { PlaytestArt } from "./playtest-view.ts";

export const PLAYTEST_BUNDLED_ART: PlaytestArt = {
  itemSrc: {
  "town.108": "assets/tile-town-108.png",
  "town.109": "assets/tile-town-109.png",
  "town.110": "assets/tile-town-110.png",
  "icons.0": "assets/tile-icons-0.png",
  "icons.1": "assets/tile-icons-1.png",
  "icons.2": "assets/tile-icons-2.png"
},
  animations: {
  "sparkle": {
    "frames": [
      "assets/playtest/anim-sparkle-0.png",
      "assets/playtest/anim-sparkle-1.png",
      "assets/playtest/anim-sparkle-2.png",
      "assets/playtest/anim-sparkle-3.png"
    ],
    "w": 16,
    "h": 16
  }
},
  parallaxes: {
  "dusk": {
    "image": "assets/playtest/parallax-dusk.png",
    "w": 128,
    "h": 64
  }
},
};
