// AUTO-GENERATED by editor/gen-assets.ts — tile sheet grids and the
// example source file each sheet's cells were cut from. Do not edit.

export interface SheetMeta {
  id: string;
  cols: number;
  rows: number;
  tile: number;
  /** Repository path of the source sheet PNG. */
  source: string;
}

export const SHEETS: SheetMeta[] = [
  {
    "id": "town",
    "cols": 12,
    "rows": 11,
    "tile": 16,
    "source": "examples/sunstone/assets/src/town-tiles.png"
  },
  {
    "id": "dun",
    "cols": 12,
    "rows": 11,
    "tile": 16,
    "source": "examples/sunstone/assets/src/dungeon-tiles.png"
  },
  {
    "id": "icons",
    "cols": 3,
    "rows": 1,
    "tile": 16,
    "source": "editor/fixtures/playtest-art/assets/src/icons.png"
  }
];
