// AUTO-GENERATED by examples/showcase/gen-assets.ts — do not edit.
import type { GameAssets } from "../../src/ui/game-assets.ts";

const PLAYER = {
    idle: ["assets/player-idle-0.png","assets/player-idle-1.png","assets/player-idle-2.png","assets/player-idle-3.png"],
    walkL: ["assets/player-left-0.png","assets/player-left-1.png","assets/player-left-2.png","assets/player-left-3.png"],
    walkR: ["assets/player-right-0.png","assets/player-right-1.png","assets/player-right-2.png","assets/player-right-3.png"],
    h: 32 as const,
  } as const;
const CURATOR = {
    idle: ["assets/curator-idle-0.png","assets/curator-idle-1.png","assets/curator-idle-2.png","assets/curator-idle-3.png"],
    walkL: ["assets/curator-left-0.png","assets/curator-left-1.png","assets/curator-left-2.png","assets/curator-left-3.png"],
    walkR: ["assets/curator-right-0.png","assets/curator-right-1.png","assets/curator-right-2.png","assets/curator-right-3.png"],
    h: 32 as const,
  } as const;
const GUIDE = {
    idle: ["assets/guide-idle-0.png","assets/guide-idle-1.png","assets/guide-idle-2.png","assets/guide-idle-3.png"],
    walkL: ["assets/guide-left-0.png","assets/guide-left-1.png","assets/guide-left-2.png","assets/guide-left-3.png"],
    walkR: ["assets/guide-right-0.png","assets/guide-right-1.png","assets/guide-right-2.png","assets/guide-right-3.png"],
    h: 32 as const,
  } as const;
const ALTERNATE = {
    idle: ["assets/guide-idle-0.png","assets/guide-idle-1.png","assets/guide-idle-2.png","assets/guide-idle-3.png"],
    walkL: ["assets/guide-left-0.png","assets/guide-left-1.png","assets/guide-left-2.png","assets/guide-left-3.png"],
    walkR: ["assets/guide-right-0.png","assets/guide-right-1.png","assets/guide-right-2.png","assets/guide-right-3.png"],
    h: 32 as const,
  } as const;

const STATIC = {"portal":"assets/portal.png","sign":"assets/sign.png","portal-1":"assets/portal-1.png","portal-2":"assets/portal-2.png","portal-3":"assets/portal-3.png","portal-4":"assets/portal-4.png","portal-5":"assets/portal-5.png","portal-6":"assets/portal-6.png","portal-7":"assets/portal-7.png","portal-8":"assets/portal-8.png","portal-9":"assets/portal-9.png","portal-10":"assets/portal-10.png","portal-11":"assets/portal-11.png","portal-12":"assets/portal-12.png","portal-13":"assets/portal-13.png"} as const;

export const GAME_ASSETS: GameAssets = {
  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 15,
  world: {"showcase-lobby":{"w":320,"h":240},"showcase-screen-effects":{"w":320,"h":240},"showcase-map-animations":{"w":320,"h":240},"showcase-runtime-visuals":{"w":320,"h":240},"showcase-movement-controls":{"w":320,"h":240},"showcase-extensions":{"w":320,"h":240},"showcase-battle":{"w":320,"h":240},"showcase-shop":{"w":320,"h":240},"hall-streaming":{"w":320,"h":240},"hall-theme":{"w":320,"h":240},"showcase-input-and-idle":{"w":320,"h":240},"hall-save":{"w":320,"h":240},"hall-attract":{"w":320,"h":240},"hall-audio":{"w":320,"h":240}},
  order: ["showcase-lobby","showcase-screen-effects","showcase-map-animations","showcase-runtime-visuals","showcase-movement-controls","showcase-extensions","showcase-battle","showcase-shop","hall-streaming","hall-theme","showcase-input-and-idle","hall-save","hall-attract","hall-audio"],
  npcSrc: { ...STATIC, curator: CURATOR, guide: GUIDE, runner: GUIDE, alternate: ALTERNATE },
  player: PLAYER, playerHeight: 32,
  stream: {
  chunkPx: 128,
  margin: 16,
  loadBudget: 2,
  ground: {
    "showcase-lobby": ["ui:tile.showcase-showcase-lobby-ground#0","ui:tile.showcase-showcase-lobby-ground#1","ui:tile.showcase-showcase-lobby-ground#2","ui:tile.showcase-showcase-lobby-ground#3","ui:tile.showcase-showcase-lobby-ground#4","ui:tile.showcase-showcase-lobby-ground#5"],
    "showcase-screen-effects": ["ui:tile.showcase-showcase-screen-effects-ground#0","ui:tile.showcase-showcase-screen-effects-ground#1","ui:tile.showcase-showcase-screen-effects-ground#2","ui:tile.showcase-showcase-screen-effects-ground#3","ui:tile.showcase-showcase-screen-effects-ground#4","ui:tile.showcase-showcase-screen-effects-ground#5"],
    "showcase-map-animations": ["ui:tile.showcase-showcase-map-animations-ground#0","ui:tile.showcase-showcase-map-animations-ground#1","ui:tile.showcase-showcase-map-animations-ground#2","ui:tile.showcase-showcase-map-animations-ground#3","ui:tile.showcase-showcase-map-animations-ground#4","ui:tile.showcase-showcase-map-animations-ground#5"],
    "showcase-runtime-visuals": ["ui:tile.showcase-showcase-runtime-visuals-ground#0","ui:tile.showcase-showcase-runtime-visuals-ground#1","ui:tile.showcase-showcase-runtime-visuals-ground#2","ui:tile.showcase-showcase-runtime-visuals-ground#3","ui:tile.showcase-showcase-runtime-visuals-ground#4","ui:tile.showcase-showcase-runtime-visuals-ground#5"],
    "showcase-movement-controls": ["ui:tile.showcase-showcase-movement-controls-ground#0","ui:tile.showcase-showcase-movement-controls-ground#1","ui:tile.showcase-showcase-movement-controls-ground#2","ui:tile.showcase-showcase-movement-controls-ground#3","ui:tile.showcase-showcase-movement-controls-ground#4","ui:tile.showcase-showcase-movement-controls-ground#5"],
    "showcase-extensions": ["ui:tile.showcase-showcase-extensions-ground#0","ui:tile.showcase-showcase-extensions-ground#1","ui:tile.showcase-showcase-extensions-ground#2","ui:tile.showcase-showcase-extensions-ground#3","ui:tile.showcase-showcase-extensions-ground#4","ui:tile.showcase-showcase-extensions-ground#5"],
    "showcase-battle": ["ui:tile.showcase-showcase-battle-ground#0","ui:tile.showcase-showcase-battle-ground#1","ui:tile.showcase-showcase-battle-ground#2","ui:tile.showcase-showcase-battle-ground#3","ui:tile.showcase-showcase-battle-ground#4","ui:tile.showcase-showcase-battle-ground#5"],
    "showcase-shop": ["ui:tile.showcase-showcase-shop-ground#0","ui:tile.showcase-showcase-shop-ground#1","ui:tile.showcase-showcase-shop-ground#2","ui:tile.showcase-showcase-shop-ground#3","ui:tile.showcase-showcase-shop-ground#4","ui:tile.showcase-showcase-shop-ground#5"],
    "hall-streaming": ["ui:tile.showcase-hall-streaming-ground#0","ui:tile.showcase-hall-streaming-ground#1","ui:tile.showcase-hall-streaming-ground#2","ui:tile.showcase-hall-streaming-ground#3","ui:tile.showcase-hall-streaming-ground#4","ui:tile.showcase-hall-streaming-ground#5"],
    "hall-theme": ["ui:tile.showcase-hall-theme-ground#0","ui:tile.showcase-hall-theme-ground#1","ui:tile.showcase-hall-theme-ground#2","ui:tile.showcase-hall-theme-ground#3","ui:tile.showcase-hall-theme-ground#4","ui:tile.showcase-hall-theme-ground#5"],
    "showcase-input-and-idle": ["ui:tile.showcase-showcase-input-and-idle-ground#0","ui:tile.showcase-showcase-input-and-idle-ground#1","ui:tile.showcase-showcase-input-and-idle-ground#2","ui:tile.showcase-showcase-input-and-idle-ground#3","ui:tile.showcase-showcase-input-and-idle-ground#4","ui:tile.showcase-showcase-input-and-idle-ground#5"],
    "hall-save": ["ui:tile.showcase-hall-save-ground#0","ui:tile.showcase-hall-save-ground#1","ui:tile.showcase-hall-save-ground#2","ui:tile.showcase-hall-save-ground#3","ui:tile.showcase-hall-save-ground#4","ui:tile.showcase-hall-save-ground#5"],
    "hall-attract": ["ui:tile.showcase-hall-attract-ground#0","ui:tile.showcase-hall-attract-ground#1","ui:tile.showcase-hall-attract-ground#2","ui:tile.showcase-hall-attract-ground#3","ui:tile.showcase-hall-attract-ground#4","ui:tile.showcase-hall-attract-ground#5"],
    "hall-audio": ["ui:tile.showcase-hall-audio-ground#0","ui:tile.showcase-hall-audio-ground#1","ui:tile.showcase-hall-audio-ground#2","ui:tile.showcase-hall-audio-ground#3","ui:tile.showcase-hall-audio-ground#4","ui:tile.showcase-hall-audio-ground#5"],
  },
  upper: {
    "showcase-lobby": ["ui:tile.showcase-showcase-lobby-upper#0","ui:tile.showcase-showcase-lobby-upper#1","ui:tile.showcase-showcase-lobby-upper#2","ui:tile.showcase-showcase-lobby-upper#3","ui:tile.showcase-showcase-lobby-upper#4","ui:tile.showcase-showcase-lobby-upper#5"],
    "showcase-screen-effects": ["ui:tile.showcase-showcase-screen-effects-upper#0","ui:tile.showcase-showcase-screen-effects-upper#1","ui:tile.showcase-showcase-screen-effects-upper#2","ui:tile.showcase-showcase-screen-effects-upper#3","ui:tile.showcase-showcase-screen-effects-upper#4","ui:tile.showcase-showcase-screen-effects-upper#5"],
    "showcase-map-animations": ["ui:tile.showcase-showcase-map-animations-upper#0","ui:tile.showcase-showcase-map-animations-upper#1","ui:tile.showcase-showcase-map-animations-upper#2","ui:tile.showcase-showcase-map-animations-upper#3","ui:tile.showcase-showcase-map-animations-upper#4","ui:tile.showcase-showcase-map-animations-upper#5"],
    "showcase-runtime-visuals": ["ui:tile.showcase-showcase-runtime-visuals-upper#0","ui:tile.showcase-showcase-runtime-visuals-upper#1","ui:tile.showcase-showcase-runtime-visuals-upper#2","ui:tile.showcase-showcase-runtime-visuals-upper#3","ui:tile.showcase-showcase-runtime-visuals-upper#4","ui:tile.showcase-showcase-runtime-visuals-upper#5"],
    "showcase-movement-controls": ["ui:tile.showcase-showcase-movement-controls-upper#0","ui:tile.showcase-showcase-movement-controls-upper#1","ui:tile.showcase-showcase-movement-controls-upper#2","ui:tile.showcase-showcase-movement-controls-upper#3","ui:tile.showcase-showcase-movement-controls-upper#4","ui:tile.showcase-showcase-movement-controls-upper#5"],
    "showcase-extensions": ["ui:tile.showcase-showcase-extensions-upper#0","ui:tile.showcase-showcase-extensions-upper#1","ui:tile.showcase-showcase-extensions-upper#2","ui:tile.showcase-showcase-extensions-upper#3","ui:tile.showcase-showcase-extensions-upper#4","ui:tile.showcase-showcase-extensions-upper#5"],
    "showcase-battle": ["ui:tile.showcase-showcase-battle-upper#0","ui:tile.showcase-showcase-battle-upper#1","ui:tile.showcase-showcase-battle-upper#2",null,null,null],
    "showcase-shop": ["ui:tile.showcase-showcase-shop-upper#0","ui:tile.showcase-showcase-shop-upper#1","ui:tile.showcase-showcase-shop-upper#2","ui:tile.showcase-showcase-shop-upper#3","ui:tile.showcase-showcase-shop-upper#4","ui:tile.showcase-showcase-shop-upper#5"],
    "hall-streaming": ["ui:tile.showcase-hall-streaming-upper#0","ui:tile.showcase-hall-streaming-upper#1","ui:tile.showcase-hall-streaming-upper#2","ui:tile.showcase-hall-streaming-upper#3","ui:tile.showcase-hall-streaming-upper#4","ui:tile.showcase-hall-streaming-upper#5"],
    "hall-theme": ["ui:tile.showcase-hall-theme-upper#0","ui:tile.showcase-hall-theme-upper#1","ui:tile.showcase-hall-theme-upper#2","ui:tile.showcase-hall-theme-upper#3","ui:tile.showcase-hall-theme-upper#4","ui:tile.showcase-hall-theme-upper#5"],
    "showcase-input-and-idle": ["ui:tile.showcase-showcase-input-and-idle-upper#0","ui:tile.showcase-showcase-input-and-idle-upper#1","ui:tile.showcase-showcase-input-and-idle-upper#2","ui:tile.showcase-showcase-input-and-idle-upper#3","ui:tile.showcase-showcase-input-and-idle-upper#4","ui:tile.showcase-showcase-input-and-idle-upper#5"],
    "hall-save": ["ui:tile.showcase-hall-save-upper#0","ui:tile.showcase-hall-save-upper#1","ui:tile.showcase-hall-save-upper#2","ui:tile.showcase-hall-save-upper#3","ui:tile.showcase-hall-save-upper#4","ui:tile.showcase-hall-save-upper#5"],
    "hall-attract": ["ui:tile.showcase-hall-attract-upper#0","ui:tile.showcase-hall-attract-upper#1","ui:tile.showcase-hall-attract-upper#2","ui:tile.showcase-hall-attract-upper#3","ui:tile.showcase-hall-attract-upper#4","ui:tile.showcase-hall-attract-upper#5"],
    "hall-audio": ["ui:tile.showcase-hall-audio-upper#0","ui:tile.showcase-hall-audio-upper#1","ui:tile.showcase-hall-audio-upper#2","ui:tile.showcase-hall-audio-upper#3","ui:tile.showcase-hall-audio-upper#4","ui:tile.showcase-hall-audio-upper#5"],
  },
  columns: {
    "showcase-lobby": 3,
    "showcase-screen-effects": 3,
    "showcase-map-animations": 3,
    "showcase-runtime-visuals": 3,
    "showcase-movement-controls": 3,
    "showcase-extensions": 3,
    "showcase-battle": 3,
    "showcase-shop": 3,
    "hall-streaming": 3,
    "hall-theme": 3,
    "showcase-input-and-idle": 3,
    "hall-save": 3,
    "hall-attract": 3,
    "hall-audio": 3,
  },
},
  animated: {
  "hall-streaming": [
    { x: 3, y: 2, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 4, y: 2, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 5, y: 2, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 3, y: 3, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 4, y: 3, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 5, y: 3, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 9, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 15, y: 9, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 16, y: 9, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 10, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 15, y: 10, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 16, y: 10, above: false, sprite: "assets/anim/spark-0.png" },
  ],
},
  anims: {
    "showcase-pulse": { frames: ["assets/map-anim/pulse-0.png","assets/map-anim/pulse-1.png","assets/map-anim/pulse-2.png","assets/map-anim/pulse-3.png","assets/map-anim/pulse-4.png","assets/map-anim/pulse-5.png","assets/map-anim/pulse-6.png","assets/map-anim/pulse-7.png","assets/map-anim/pulse-8.png","assets/map-anim/pulse-9.png"], w: 64, h: 64 },
    "showcase-ring": { frames: ["assets/map-anim/pulse-9.png","assets/map-anim/pulse-8.png","assets/map-anim/pulse-7.png","assets/map-anim/pulse-6.png","assets/map-anim/pulse-5.png","assets/map-anim/pulse-4.png","assets/map-anim/pulse-3.png","assets/map-anim/pulse-2.png","assets/map-anim/pulse-1.png","assets/map-anim/pulse-0.png"], w: 64, h: 64 },
  },
  layers: {
    gate: { placement: "above", mode: "streamed", defaultVariant: "closed", defaultVisible: true, variants: { closed: { refs: { "showcase-runtime-visuals": [null,"ui:tile.showcase-gate#1",null,null,null,null] }, columns: { "showcase-runtime-visuals": 3 }, chunkPx: 128 } } },
    weather: { placement: "screen", defaultVisible: false, variants: { day: { color: "#ffe8a040", opacity: 0.32 }, dusk: { color: "#ef6a8058", opacity: 0.42 }, night: { color: "#163a9070", opacity: 0.52 } } },
    backdrop: { placement: "screen", defaultVisible: false, variants: { gallery: { color: "#251144", opacity: 1 }, stars: { color: "#07142e", opacity: 1 } } },
  },
};

export const SHOWCASE_ART = { face: "assets/face-curator.png", battlePlayer: "assets/battle-player.png", battleEnemy: "assets/battle-enemy.png", battleBackground: "assets/battle-background.png" } as const;
