// AUTO-GENERATED by examples/showcase/gen-assets.ts — do not edit.
import type { GameAssets } from "../../src/ui/game-assets.ts";

const PLAYER = {
    idle: ["assets/player-idle-0.png","assets/player-idle-1.png","assets/player-idle-2.png","assets/player-idle-3.png"],
    walkL: ["assets/player-left-0.png","assets/player-left-1.png","assets/player-left-2.png","assets/player-left-3.png"],
    walkR: ["assets/player-right-0.png","assets/player-right-1.png","assets/player-right-2.png","assets/player-right-3.png"],
    h: 32 as const,
  } as const;
const CURATOR = {
    idle: ["assets/curator-idle-0.png","assets/curator-idle-1.png","assets/curator-idle-2.png","assets/curator-idle-3.png"],
    walkL: ["assets/curator-left-0.png","assets/curator-left-1.png","assets/curator-left-2.png","assets/curator-left-3.png"],
    walkR: ["assets/curator-right-0.png","assets/curator-right-1.png","assets/curator-right-2.png","assets/curator-right-3.png"],
    h: 32 as const,
  } as const;
const GUIDE = {
    idle: ["assets/guide-idle-0.png","assets/guide-idle-1.png","assets/guide-idle-2.png","assets/guide-idle-3.png"],
    walkL: ["assets/guide-left-0.png","assets/guide-left-1.png","assets/guide-left-2.png","assets/guide-left-3.png"],
    walkR: ["assets/guide-right-0.png","assets/guide-right-1.png","assets/guide-right-2.png","assets/guide-right-3.png"],
    h: 32 as const,
  } as const;
const ALTERNATE = {
    idle: ["assets/alternate-idle-0.png","assets/alternate-idle-1.png","assets/alternate-idle-2.png","assets/alternate-idle-3.png"],
    walkL: ["assets/alternate-left-0.png","assets/alternate-left-1.png","assets/alternate-left-2.png","assets/alternate-left-3.png"],
    walkR: ["assets/alternate-right-0.png","assets/alternate-right-1.png","assets/alternate-right-2.png","assets/alternate-right-3.png"],
    h: 32 as const,
  } as const;

const STATIC = {"sign":"assets/sign.png"} as const;

export const GAME_ASSETS: GameAssets = {
  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 30,
  world: {"showcase-lobby":{"w":480,"h":272},"showcase-screen-effects":{"w":480,"h":272},"showcase-map-animations":{"w":480,"h":272},"showcase-runtime-visuals":{"w":480,"h":272},"showcase-movement-controls":{"w":480,"h":272},"showcase-extensions":{"w":480,"h":272},"showcase-battle":{"w":480,"h":272},"showcase-shop":{"w":480,"h":272},"hall-streaming":{"w":480,"h":272},"hall-theme":{"w":480,"h":272},"showcase-input-and-idle":{"w":480,"h":272},"hall-save":{"w":480,"h":272},"hall-attract":{"w":480,"h":272},"hall-audio":{"w":480,"h":272},"hall-registration":{"w":480,"h":272}},
  order: ["showcase-lobby","showcase-screen-effects","showcase-map-animations","showcase-runtime-visuals","showcase-movement-controls","showcase-extensions","showcase-battle","showcase-shop","hall-streaming","hall-theme","showcase-input-and-idle","hall-save","hall-attract","hall-audio","hall-registration"],
  npcSrc: { ...STATIC, curator: CURATOR, guide: GUIDE, runner: GUIDE, alternate: ALTERNATE },
  player: PLAYER, playerHeight: 32,
  stream: {
  chunkPx: 128,
  margin: 16,
  loadBudget: 2,
  ground: {
    "showcase-lobby": ["ui:tile.showcase-showcase-lobby-ground#0","ui:tile.showcase-showcase-lobby-ground#1","ui:tile.showcase-showcase-lobby-ground#2","ui:tile.showcase-showcase-lobby-ground#3","ui:tile.showcase-showcase-lobby-ground#4","ui:tile.showcase-showcase-lobby-ground#5","ui:tile.showcase-showcase-lobby-ground#6","ui:tile.showcase-showcase-lobby-ground#7","ui:tile.showcase-showcase-lobby-ground#8","ui:tile.showcase-showcase-lobby-ground#9","ui:tile.showcase-showcase-lobby-ground#10","ui:tile.showcase-showcase-lobby-ground#11"],
    "showcase-screen-effects": ["ui:tile.showcase-showcase-screen-effects-ground#0","ui:tile.showcase-showcase-screen-effects-ground#1","ui:tile.showcase-showcase-screen-effects-ground#2","ui:tile.showcase-showcase-screen-effects-ground#3","ui:tile.showcase-showcase-screen-effects-ground#4","ui:tile.showcase-showcase-screen-effects-ground#5","ui:tile.showcase-showcase-screen-effects-ground#6","ui:tile.showcase-showcase-screen-effects-ground#7","ui:tile.showcase-showcase-screen-effects-ground#8","ui:tile.showcase-showcase-screen-effects-ground#9","ui:tile.showcase-showcase-screen-effects-ground#10","ui:tile.showcase-showcase-screen-effects-ground#11"],
    "showcase-map-animations": ["ui:tile.showcase-showcase-map-animations-ground#0","ui:tile.showcase-showcase-map-animations-ground#1","ui:tile.showcase-showcase-map-animations-ground#2","ui:tile.showcase-showcase-map-animations-ground#3","ui:tile.showcase-showcase-map-animations-ground#4","ui:tile.showcase-showcase-map-animations-ground#5","ui:tile.showcase-showcase-map-animations-ground#6","ui:tile.showcase-showcase-map-animations-ground#7","ui:tile.showcase-showcase-map-animations-ground#8","ui:tile.showcase-showcase-map-animations-ground#9","ui:tile.showcase-showcase-map-animations-ground#10","ui:tile.showcase-showcase-map-animations-ground#11"],
    "showcase-runtime-visuals": ["ui:tile.showcase-showcase-runtime-visuals-ground#0","ui:tile.showcase-showcase-runtime-visuals-ground#1","ui:tile.showcase-showcase-runtime-visuals-ground#2","ui:tile.showcase-showcase-runtime-visuals-ground#3","ui:tile.showcase-showcase-runtime-visuals-ground#4","ui:tile.showcase-showcase-runtime-visuals-ground#5","ui:tile.showcase-showcase-runtime-visuals-ground#6","ui:tile.showcase-showcase-runtime-visuals-ground#7","ui:tile.showcase-showcase-runtime-visuals-ground#8","ui:tile.showcase-showcase-runtime-visuals-ground#9","ui:tile.showcase-showcase-runtime-visuals-ground#10","ui:tile.showcase-showcase-runtime-visuals-ground#11"],
    "showcase-movement-controls": ["ui:tile.showcase-showcase-movement-controls-ground#0","ui:tile.showcase-showcase-movement-controls-ground#1","ui:tile.showcase-showcase-movement-controls-ground#2","ui:tile.showcase-showcase-movement-controls-ground#3","ui:tile.showcase-showcase-movement-controls-ground#4","ui:tile.showcase-showcase-movement-controls-ground#5","ui:tile.showcase-showcase-movement-controls-ground#6","ui:tile.showcase-showcase-movement-controls-ground#7","ui:tile.showcase-showcase-movement-controls-ground#8","ui:tile.showcase-showcase-movement-controls-ground#9","ui:tile.showcase-showcase-movement-controls-ground#10","ui:tile.showcase-showcase-movement-controls-ground#11"],
    "showcase-extensions": ["ui:tile.showcase-showcase-extensions-ground#0","ui:tile.showcase-showcase-extensions-ground#1","ui:tile.showcase-showcase-extensions-ground#2","ui:tile.showcase-showcase-extensions-ground#3","ui:tile.showcase-showcase-extensions-ground#4","ui:tile.showcase-showcase-extensions-ground#5","ui:tile.showcase-showcase-extensions-ground#6","ui:tile.showcase-showcase-extensions-ground#7","ui:tile.showcase-showcase-extensions-ground#8","ui:tile.showcase-showcase-extensions-ground#9","ui:tile.showcase-showcase-extensions-ground#10","ui:tile.showcase-showcase-extensions-ground#11"],
    "showcase-battle": ["ui:tile.showcase-showcase-battle-ground#0","ui:tile.showcase-showcase-battle-ground#1","ui:tile.showcase-showcase-battle-ground#2","ui:tile.showcase-showcase-battle-ground#3","ui:tile.showcase-showcase-battle-ground#4","ui:tile.showcase-showcase-battle-ground#5","ui:tile.showcase-showcase-battle-ground#6","ui:tile.showcase-showcase-battle-ground#7","ui:tile.showcase-showcase-battle-ground#8","ui:tile.showcase-showcase-battle-ground#9","ui:tile.showcase-showcase-battle-ground#10","ui:tile.showcase-showcase-battle-ground#11"],
    "showcase-shop": ["ui:tile.showcase-showcase-shop-ground#0","ui:tile.showcase-showcase-shop-ground#1","ui:tile.showcase-showcase-shop-ground#2","ui:tile.showcase-showcase-shop-ground#3","ui:tile.showcase-showcase-shop-ground#4","ui:tile.showcase-showcase-shop-ground#5","ui:tile.showcase-showcase-shop-ground#6","ui:tile.showcase-showcase-shop-ground#7","ui:tile.showcase-showcase-shop-ground#8","ui:tile.showcase-showcase-shop-ground#9","ui:tile.showcase-showcase-shop-ground#10","ui:tile.showcase-showcase-shop-ground#11"],
    "hall-streaming": ["ui:tile.showcase-hall-streaming-ground#0","ui:tile.showcase-hall-streaming-ground#1","ui:tile.showcase-hall-streaming-ground#2","ui:tile.showcase-hall-streaming-ground#3","ui:tile.showcase-hall-streaming-ground#4","ui:tile.showcase-hall-streaming-ground#5","ui:tile.showcase-hall-streaming-ground#6","ui:tile.showcase-hall-streaming-ground#7","ui:tile.showcase-hall-streaming-ground#8","ui:tile.showcase-hall-streaming-ground#9","ui:tile.showcase-hall-streaming-ground#10","ui:tile.showcase-hall-streaming-ground#11"],
    "hall-theme": ["ui:tile.showcase-hall-theme-ground#0","ui:tile.showcase-hall-theme-ground#1","ui:tile.showcase-hall-theme-ground#2","ui:tile.showcase-hall-theme-ground#3","ui:tile.showcase-hall-theme-ground#4","ui:tile.showcase-hall-theme-ground#5","ui:tile.showcase-hall-theme-ground#6","ui:tile.showcase-hall-theme-ground#7","ui:tile.showcase-hall-theme-ground#8","ui:tile.showcase-hall-theme-ground#9","ui:tile.showcase-hall-theme-ground#10","ui:tile.showcase-hall-theme-ground#11"],
    "showcase-input-and-idle": ["ui:tile.showcase-showcase-input-and-idle-ground#0","ui:tile.showcase-showcase-input-and-idle-ground#1","ui:tile.showcase-showcase-input-and-idle-ground#2","ui:tile.showcase-showcase-input-and-idle-ground#3","ui:tile.showcase-showcase-input-and-idle-ground#4","ui:tile.showcase-showcase-input-and-idle-ground#5","ui:tile.showcase-showcase-input-and-idle-ground#6","ui:tile.showcase-showcase-input-and-idle-ground#7","ui:tile.showcase-showcase-input-and-idle-ground#8","ui:tile.showcase-showcase-input-and-idle-ground#9","ui:tile.showcase-showcase-input-and-idle-ground#10","ui:tile.showcase-showcase-input-and-idle-ground#11"],
    "hall-save": ["ui:tile.showcase-hall-save-ground#0","ui:tile.showcase-hall-save-ground#1","ui:tile.showcase-hall-save-ground#2","ui:tile.showcase-hall-save-ground#3","ui:tile.showcase-hall-save-ground#4","ui:tile.showcase-hall-save-ground#5","ui:tile.showcase-hall-save-ground#6","ui:tile.showcase-hall-save-ground#7","ui:tile.showcase-hall-save-ground#8","ui:tile.showcase-hall-save-ground#9","ui:tile.showcase-hall-save-ground#10","ui:tile.showcase-hall-save-ground#11"],
    "hall-attract": ["ui:tile.showcase-hall-attract-ground#0","ui:tile.showcase-hall-attract-ground#1","ui:tile.showcase-hall-attract-ground#2","ui:tile.showcase-hall-attract-ground#3","ui:tile.showcase-hall-attract-ground#4","ui:tile.showcase-hall-attract-ground#5","ui:tile.showcase-hall-attract-ground#6","ui:tile.showcase-hall-attract-ground#7","ui:tile.showcase-hall-attract-ground#8","ui:tile.showcase-hall-attract-ground#9","ui:tile.showcase-hall-attract-ground#10","ui:tile.showcase-hall-attract-ground#11"],
    "hall-audio": ["ui:tile.showcase-hall-audio-ground#0","ui:tile.showcase-hall-audio-ground#1","ui:tile.showcase-hall-audio-ground#2","ui:tile.showcase-hall-audio-ground#3","ui:tile.showcase-hall-audio-ground#4","ui:tile.showcase-hall-audio-ground#5","ui:tile.showcase-hall-audio-ground#6","ui:tile.showcase-hall-audio-ground#7","ui:tile.showcase-hall-audio-ground#8","ui:tile.showcase-hall-audio-ground#9","ui:tile.showcase-hall-audio-ground#10","ui:tile.showcase-hall-audio-ground#11"],
    "hall-registration": ["ui:tile.showcase-hall-registration-ground#0","ui:tile.showcase-hall-registration-ground#1","ui:tile.showcase-hall-registration-ground#2","ui:tile.showcase-hall-registration-ground#3","ui:tile.showcase-hall-registration-ground#4","ui:tile.showcase-hall-registration-ground#5","ui:tile.showcase-hall-registration-ground#6","ui:tile.showcase-hall-registration-ground#7","ui:tile.showcase-hall-registration-ground#8","ui:tile.showcase-hall-registration-ground#9","ui:tile.showcase-hall-registration-ground#10","ui:tile.showcase-hall-registration-ground#11"],
  },
  upper: {
    "showcase-lobby": ["ui:tile.showcase-showcase-lobby-upper#0","ui:tile.showcase-showcase-lobby-upper#1","ui:tile.showcase-showcase-lobby-upper#2","ui:tile.showcase-showcase-lobby-upper#3","ui:tile.showcase-showcase-lobby-upper#4","ui:tile.showcase-showcase-lobby-upper#5","ui:tile.showcase-showcase-lobby-upper#6","ui:tile.showcase-showcase-lobby-upper#7",null,null,null,null],
    "showcase-screen-effects": ["ui:tile.showcase-showcase-screen-effects-upper#0","ui:tile.showcase-showcase-screen-effects-upper#1","ui:tile.showcase-showcase-screen-effects-upper#2",null,"ui:tile.showcase-showcase-screen-effects-upper#4","ui:tile.showcase-showcase-screen-effects-upper#5","ui:tile.showcase-showcase-screen-effects-upper#6","ui:tile.showcase-showcase-screen-effects-upper#7",null,null,null,null],
    "showcase-map-animations": [null,"ui:tile.showcase-showcase-map-animations-upper#1","ui:tile.showcase-showcase-map-animations-upper#2",null,"ui:tile.showcase-showcase-map-animations-upper#4",null,"ui:tile.showcase-showcase-map-animations-upper#6","ui:tile.showcase-showcase-map-animations-upper#7",null,null,null,null],
    "showcase-runtime-visuals": ["ui:tile.showcase-showcase-runtime-visuals-upper#0","ui:tile.showcase-showcase-runtime-visuals-upper#1","ui:tile.showcase-showcase-runtime-visuals-upper#2","ui:tile.showcase-showcase-runtime-visuals-upper#3","ui:tile.showcase-showcase-runtime-visuals-upper#4",null,null,null,null,null,null,null],
    "showcase-movement-controls": [null,null,"ui:tile.showcase-showcase-movement-controls-upper#2","ui:tile.showcase-showcase-movement-controls-upper#3","ui:tile.showcase-showcase-movement-controls-upper#4","ui:tile.showcase-showcase-movement-controls-upper#5",null,"ui:tile.showcase-showcase-movement-controls-upper#7",null,null,null,null],
    "showcase-extensions": ["ui:tile.showcase-showcase-extensions-upper#0","ui:tile.showcase-showcase-extensions-upper#1","ui:tile.showcase-showcase-extensions-upper#2","ui:tile.showcase-showcase-extensions-upper#3","ui:tile.showcase-showcase-extensions-upper#4",null,"ui:tile.showcase-showcase-extensions-upper#6",null,null,null,null,null],
    "showcase-battle": ["ui:tile.showcase-showcase-battle-upper#0","ui:tile.showcase-showcase-battle-upper#1","ui:tile.showcase-showcase-battle-upper#2","ui:tile.showcase-showcase-battle-upper#3","ui:tile.showcase-showcase-battle-upper#4",null,null,"ui:tile.showcase-showcase-battle-upper#7",null,null,null,null],
    "showcase-shop": ["ui:tile.showcase-showcase-shop-upper#0",null,"ui:tile.showcase-showcase-shop-upper#2","ui:tile.showcase-showcase-shop-upper#3","ui:tile.showcase-showcase-shop-upper#4","ui:tile.showcase-showcase-shop-upper#5","ui:tile.showcase-showcase-shop-upper#6","ui:tile.showcase-showcase-shop-upper#7",null,null,null,null],
    "hall-streaming": ["ui:tile.showcase-hall-streaming-upper#0","ui:tile.showcase-hall-streaming-upper#1","ui:tile.showcase-hall-streaming-upper#2","ui:tile.showcase-hall-streaming-upper#3","ui:tile.showcase-hall-streaming-upper#4",null,"ui:tile.showcase-hall-streaming-upper#6","ui:tile.showcase-hall-streaming-upper#7",null,null,null,null],
    "hall-theme": ["ui:tile.showcase-hall-theme-upper#0","ui:tile.showcase-hall-theme-upper#1","ui:tile.showcase-hall-theme-upper#2","ui:tile.showcase-hall-theme-upper#3","ui:tile.showcase-hall-theme-upper#4",null,null,null,null,null,null,null],
    "showcase-input-and-idle": ["ui:tile.showcase-showcase-input-and-idle-upper#0",null,"ui:tile.showcase-showcase-input-and-idle-upper#2","ui:tile.showcase-showcase-input-and-idle-upper#3","ui:tile.showcase-showcase-input-and-idle-upper#4",null,null,null,null,null,null,null],
    "hall-save": ["ui:tile.showcase-hall-save-upper#0","ui:tile.showcase-hall-save-upper#1","ui:tile.showcase-hall-save-upper#2","ui:tile.showcase-hall-save-upper#3","ui:tile.showcase-hall-save-upper#4","ui:tile.showcase-hall-save-upper#5","ui:tile.showcase-hall-save-upper#6",null,null,null,null,null],
    "hall-attract": [null,"ui:tile.showcase-hall-attract-upper#1",null,null,"ui:tile.showcase-hall-attract-upper#4","ui:tile.showcase-hall-attract-upper#5","ui:tile.showcase-hall-attract-upper#6",null,null,null,null,null],
    "hall-audio": ["ui:tile.showcase-hall-audio-upper#0","ui:tile.showcase-hall-audio-upper#1","ui:tile.showcase-hall-audio-upper#2","ui:tile.showcase-hall-audio-upper#3","ui:tile.showcase-hall-audio-upper#4",null,null,null,null,null,null,null],
    "hall-registration": ["ui:tile.showcase-hall-registration-upper#0","ui:tile.showcase-hall-registration-upper#1","ui:tile.showcase-hall-registration-upper#2","ui:tile.showcase-hall-registration-upper#3","ui:tile.showcase-hall-registration-upper#4","ui:tile.showcase-hall-registration-upper#5","ui:tile.showcase-hall-registration-upper#6",null,null,null,null,null],
  },
  columns: {
    "showcase-lobby": 4,
    "showcase-screen-effects": 4,
    "showcase-map-animations": 4,
    "showcase-runtime-visuals": 4,
    "showcase-movement-controls": 4,
    "showcase-extensions": 4,
    "showcase-battle": 4,
    "showcase-shop": 4,
    "hall-streaming": 4,
    "hall-theme": 4,
    "showcase-input-and-idle": 4,
    "hall-save": 4,
    "hall-attract": 4,
    "hall-audio": 4,
    "hall-registration": 4,
  },
},
  animated: {
  "hall-streaming": [
    { x: 13, y: 2, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 2, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 13, y: 3, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 3, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 13, y: 4, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 4, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 13, y: 10, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 10, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 13, y: 11, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 11, above: true, sprite: "assets/anim/spark-0.png" },
    { x: 13, y: 12, above: false, sprite: "assets/anim/spark-0.png" },
    { x: 14, y: 12, above: false, sprite: "assets/anim/spark-0.png" },
  ],
},
  anims: {
    "showcase-pulse": { frames: ["assets/map-anim/pulse-0.png","assets/map-anim/pulse-1.png","assets/map-anim/pulse-2.png","assets/map-anim/pulse-3.png","assets/map-anim/pulse-4.png","assets/map-anim/pulse-5.png","assets/map-anim/pulse-6.png","assets/map-anim/pulse-7.png","assets/map-anim/pulse-8.png","assets/map-anim/pulse-9.png"], w: 64, h: 64 },
    "showcase-ring": { frames: ["assets/map-anim/pulse-9.png","assets/map-anim/pulse-8.png","assets/map-anim/pulse-7.png","assets/map-anim/pulse-6.png","assets/map-anim/pulse-5.png","assets/map-anim/pulse-4.png","assets/map-anim/pulse-3.png","assets/map-anim/pulse-2.png","assets/map-anim/pulse-1.png","assets/map-anim/pulse-0.png"], w: 64, h: 64 },
  },
  layers: {
    gate: { placement: "above", mode: "streamed", defaultVariant: "closed", defaultVisible: true, variants: { closed: { refs: { "showcase-runtime-visuals": [null,"ui:tile.showcase-gate#1",null,null,null,null,null,null,null,null,null,null] }, columns: { "showcase-runtime-visuals": 4 }, chunkPx: 128 } } },
    weather: { placement: "screen", defaultVisible: false, variants: { day: { color: "#ffe8a040", opacity: 0.32 }, dusk: { color: "#ef6a8058", opacity: 0.42 }, night: { color: "#163a9070", opacity: 0.52 } } },
    backdrop: { placement: "screen", defaultVisible: false, variants: { gallery: { color: "#251144", opacity: 1 }, stars: { color: "#07142e", opacity: 1 } } },
  },
};

export const SHOWCASE_ART = { face: "assets/face-curator.png", guideFace: "assets/face-guide.png", visitorFace: "assets/face-visitor.png", battlePlayer: "assets/battle-player.png", battleEnemy: "assets/battle-enemy.png", battleBackground: "assets/battle-background.png" } as const;
