// src/engine/tape.ts — button tapes as data: one u16 mask per 60 Hz
// source frame, stored run-length encoded as [mask, count] pairs.
//
// A game ships its winning playthrough as a frozen RLE tape (generated by
// its deterministic journey driver) and the attract controller
// (attract.ts) replays it. parseTapeDocument() reads the PocketJS devtools
// tape shape ({v, frames, masks:[[mask,count],…]}, as tools/tape.ts
// writes it) and rejects anything malformed, so a corrupt override can
// never boot a game to a black screen. Pure: no host imports.

import type { WorldTraversalMode } from "./types.ts";

/** Expand run-length [mask,count] pairs to one mask per frame. */
export function expandTapeRuns(runs: readonly (readonly [number, number])[]): number[] {
  const out: number[] = [];
  for (const [mask, count] of runs) {
    for (let i = 0; i < count; i++) out.push(mask >>> 0);
  }
  return out;
}

/** Run-length encode one mask per frame (the inverse of expandTapeRuns). */
export function tapeRunsFromMasks(masks: readonly number[]): [number, number][] {
  const runs: [number, number][] = [];
  for (const mask of masks) {
    const last = runs[runs.length - 1];
    if (last && last[0] === mask) last[1]++;
    else runs.push([mask, 1]);
  }
  return runs;
}

interface TapeDocument {
  v?: unknown;
  frames?: unknown;
  masks?: unknown;
  worldTraversal?: unknown;
}

export interface ParsedTapeDocument {
  masks: number[];
  /** Missing on older tapes and therefore normalized to legacy-transfer. */
  worldTraversal: WorldTraversalMode;
}

/** Parse masks together with the transfer-timeline identity that gives those
 * inputs meaning. Unknown identities are rejected instead of being guessed. */
export function parseTapeDocumentWithIdentity(text: string): ParsedTapeDocument | null {
  let doc: TapeDocument;
  try {
    doc = JSON.parse(text) as TapeDocument;
  } catch {
    return null;
  }
  if (![1, 2, 3].includes(doc.v as number)) return null;
  if (typeof doc.frames !== "number" || !Number.isInteger(doc.frames) || doc.frames < 1) return null;
  if (!Array.isArray(doc.masks)) return null;
  if (
    doc.worldTraversal !== undefined &&
    doc.worldTraversal !== "legacy-transfer" &&
    doc.worldTraversal !== "seamless-v1"
  ) return null;
  const out: number[] = [];
  for (const run of doc.masks) {
    if (!Array.isArray(run) || run.length !== 2) return null;
    const mask = run[0];
    const count = run[1];
    if (typeof mask !== "number" || typeof count !== "number") return null;
    if (!Number.isInteger(mask) || mask < 0 || mask > 0xffff) return null;
    if (!Number.isInteger(count) || count < 1) return null;
    for (let i = 0; i < count; i++) out.push(mask);
  }
  if (out.length === 0) return null;
  if (doc.frames !== out.length) return null;
  return {
    masks: out,
    worldTraversal: doc.worldTraversal ?? "legacy-transfer",
  };
}

/** Parse a devtools tape document into one mask per frame, or null when
 *  the text is not a well-formed, self-consistent tape. */
export function parseTapeDocument(text: string): number[] | null {
  return parseTapeDocumentWithIdentity(text)?.masks ?? null;
}
