// AUTO-GENERATED by tests/fixtures/kg1-name-input/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

const WALKER = {
  idle: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkL: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
  walkR: ["assets/walker.png", "assets/walker.png", "assets/walker.png", "assets/walker.png"] as const,
};

export const GAME_ASSETS: GameAssets = {
  ground: { "kg1-name-field": ["assets/map-kg1-name-field-ground.png"] },
  upper: { "kg1-name-field": ["assets/map-kg1-name-field-upper.png"] },
  chunkColumns: { "kg1-name-field": 1 },
  maxChunks: 1,
  world: { "kg1-name-field": { w: 64, h: 64 } },
  order: ["kg1-name-field"],
  npcSrc: {},
  player: WALKER,
};
