// Deterministic visual and audio assets for the KAU1 host-audio fixture.
// Every generated file lives below assets/, which the repository ignores.

import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import { bakeMapChunks, groundChunkAsset, upperChunkAsset } from "../../../tools/lib/chunks.ts";
import { CHUNK_PX, TILE } from "../../../src/engine/tiles.ts";
import { MAP, MAP_ID } from "./fixture-data.ts";

const HERE = import.meta.dir;
const ASSETS = join(HERE, "assets");
mkdirSync(ASSETS, { recursive: true });

function tile(): Uint8Array {
  const rgba = new Uint8Array(TILE * TILE * 4);
  for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < TILE; x++) {
      const light = ((x >> 2) + (y >> 2)) % 2 === 0;
      rgba.set(light ? [22, 58, 70, 255] : [17, 43, 54, 255], (y * TILE + x) * 4);
    }
  }
  return rgba;
}

function walker(): Uint8Array {
  const rgba = new Uint8Array(TILE * TILE * 4);
  for (let y = 2; y < 15; y++) {
    for (let x = 4; x < 12; x++) {
      const edge = x === 4 || x === 11 || y === 2 || y === 14;
      rgba.set(edge ? [25, 20, 35, 255] : [244, 190, 70, 255], (y * TILE + x) * 4);
    }
  }
  return rgba;
}

function toneWav(): Uint8Array {
  const sampleRate = 11_025;
  const frames = 128;
  const dataBytes = frames * 2;
  const bytes = new Uint8Array(44 + dataBytes);
  const view = new DataView(bytes.buffer);
  const ascii = (offset: number, text: string): void => {
    for (let i = 0; i < text.length; i++) bytes[offset + i] = text.charCodeAt(i);
  };
  ascii(0, "RIFF");
  view.setUint32(4, 36 + dataBytes, true);
  ascii(8, "WAVE");
  ascii(12, "fmt ");
  view.setUint32(16, 16, true);
  view.setUint16(20, 1, true); // PCM
  view.setUint16(22, 1, true); // mono
  view.setUint32(24, sampleRate, true);
  view.setUint32(28, sampleRate * 2, true);
  view.setUint16(32, 2, true);
  view.setUint16(34, 16, true);
  ascii(36, "data");
  view.setUint32(40, dataBytes, true);
  for (let frame = 0; frame < frames; frame++) {
    // A short deterministic square tone; no floating-point oscillator or
    // platform-dependent encoder participates in the generated bytes.
    view.setInt16(44 + frame * 2, (frame & 8) === 0 ? 6_000 : -6_000, true);
  }
  return bytes;
}

const ground = tile();
const baked = bakeMapChunks(MAP, () => ground, ground);
const chunkCount = baked.columns * baked.rows;
for (let index = 0; index < chunkCount; index++) {
  writeFileSync(
    join(HERE, groundChunkAsset(MAP_ID, index, chunkCount)),
    encodePNG(baked.ground[index]!, CHUNK_PX, CHUNK_PX),
  );
  writeFileSync(
    join(HERE, upperChunkAsset(MAP_ID, index, chunkCount)),
    encodePNG(baked.upper[index]!, CHUNK_PX, CHUNK_PX),
  );
}
writeFileSync(join(ASSETS, "walker.png"), encodePNG(walker(), TILE, TILE));
writeFileSync(join(ASSETS, "tone.wav"), toneWav());

console.log("kau1-audio fixture: 4x4 visible map, 16x16 walker, 128-frame PCM16 WAV");
