// tools/preview/gen-assets.ts — copy the editor playtest art this app shares.
//
// The preview host renders arbitrary rpgkit-project/v1 documents through the
// editor's playtest asset synthesis (editor/engine/playtest-view.ts), which
// dresses every sheet cell in the editor's baked Kenney tile cells and uses
// the editor's placeholder player/NPC frames. Those bytes are committed under
// editor/assets/playtest (regenerated by editor/gen-assets.ts from the
// examples' sheets); this script copies them next to the app so the PocketJS
// pak builder resolves them, and writes the two manifests.
//
// Outputs (committed; every byte is a copy of editor/assets/playtest):
//   assets/playtest/*        player/NPC frames and the two sheet TILESETs
//   images.json              PSM marks for the PNGs
//   pak.json                 the two raw TILESET entries

import { copyFileSync, mkdirSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

const HERE = resolve(import.meta.dir);
const SRC = resolve(HERE, "..", "..", "editor", "assets", "playtest");
const DST = join(HERE, "assets", "playtest");

mkdirSync(join(HERE, "assets"), { recursive: true });
rmSync(DST, { recursive: true, force: true });
mkdirSync(DST, { recursive: true });
for (const name of readdirSync(SRC).sort()) copyFileSync(join(SRC, name), join(DST, name));

const pngs = readdirSync(DST).filter((name) => name.endsWith(".png")).sort();
const images = Object.fromEntries(pngs.map((name) => [`assets/playtest/${name}`, { psm: 3 }]));
writeFileSync(join(HERE, "images.json"), JSON.stringify(images, null, 2) + "\n");

writeFileSync(
  join(HERE, "pak.json"),
  JSON.stringify(
    [
      { key: "ui:tile.editor-sheet-town", file: "assets/playtest/sheet-town.pkts" },
      { key: "ui:tile.editor-sheet-dun", file: "assets/playtest/sheet-dun.pkts" },
    ],
    null,
    2,
  ) + "\n",
);
console.log(`preview: copied ${pngs.length} PNGs and 2 TILESET sheets from editor/assets/playtest`);
