// AUTO-GENERATED by tests/fixtures/streamed/gen-assets.ts — do not edit.
import type { GameAssets } from "../../../src/ui/game-assets.ts";

export const GAME_ASSETS: GameAssets = {
  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0,
  world: {
    "wide-field": { w: 1024, h: 640 },
    "violet-harbor": { w: 640, h: 576 },
  },
  order: ["wide-field","violet-harbor"],
  npcSrc: {},
  player: { idle: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"], walkL: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"], walkR: ["assets/player.png", "assets/player.png", "assets/player.png", "assets/player.png"] },
  stream: {
  chunkPx: 256,
  ground: {
    "wide-field": ["ui:tile.fixture-wide-field-ground#0","ui:tile.fixture-wide-field-ground#1","ui:tile.fixture-wide-field-ground#2","ui:tile.fixture-wide-field-ground#3","ui:tile.fixture-wide-field-ground#4","ui:tile.fixture-wide-field-ground#5","ui:tile.fixture-wide-field-ground#6","ui:tile.fixture-wide-field-ground#7","ui:tile.fixture-wide-field-ground#8","ui:tile.fixture-wide-field-ground#9","ui:tile.fixture-wide-field-ground#10","ui:tile.fixture-wide-field-ground#11"],
    "violet-harbor": ["ui:tile.fixture-violet-harbor-ground#0","ui:tile.fixture-violet-harbor-ground#1","ui:tile.fixture-violet-harbor-ground#2","ui:tile.fixture-violet-harbor-ground#3","ui:tile.fixture-violet-harbor-ground#4","ui:tile.fixture-violet-harbor-ground#5","ui:tile.fixture-violet-harbor-ground#6","ui:tile.fixture-violet-harbor-ground#7","ui:tile.fixture-violet-harbor-ground#8"],
  },
  upper: {
    "wide-field": [null,"ui:tile.fixture-wide-field-upper#1",null,null,null,null,null,null,null,null,null,null],
    "violet-harbor": [null,null,null,null,null,null,null,null,null],
  },
  columns: {
    "wide-field": 4,
    "violet-harbor": 3,
  },
},
  layers: {
    ground: { placement: "ground", mode: "streamed", variants: { sparse: { refs: { "wide-field": [null,"ui:tile.fixture-wide-field-upper#1",null,null,null,null,null,null,null,null,null,null] }, columns: { "wide-field": 4 }, chunkPx: 256 } } },
    upper: { placement: "upper", mode: "streamed", variants: {} },
  },
};
