// Deterministically build the streamed fixture's TILESET blobs, pak.json,
// player image and generated GameAssets manifest.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import {
  encodeStreamedLayer,
  pakManifest,
  streamEntryFile,
  streamManifestSource,
  type StreamEntry,
  type StreamedLayer,
} from "../../../tools/lib/stream.ts";
import {
  FIELD_CHUNK_COLOURS,
  FIELD_ID,
  FIELD_SIZE,
  HARBOR_CHUNK_COLOURS,
  HARBOR_ID,
  HARBOR_SIZE,
  PLAYER_COLOUR,
  ROOF_COLOUR,
  STREAM_CHUNK,
  type Rgba,
} from "./fixture-data.ts";

const HERE = import.meta.dir;
const TILE = 16;

interface FixtureMap {
  id: string;
  width: number;
  height: number;
  colours: readonly Rgba[];
  roof: boolean;
}

const maps: FixtureMap[] = [
  { id: FIELD_ID, ...FIELD_SIZE, colours: FIELD_CHUNK_COLOURS, roof: true },
  { id: HARBOR_ID, ...HARBOR_SIZE, colours: HARBOR_CHUNK_COLOURS, roof: false },
];

function chunksFor(map: FixtureMap, upper: boolean): { chunks: Uint8Array[]; columns: number; rows: number } {
  const widthPx = map.width * TILE;
  const heightPx = map.height * TILE;
  const columns = Math.ceil(widthPx / STREAM_CHUNK);
  const rows = Math.ceil(heightPx / STREAM_CHUNK);
  const chunks: Uint8Array[] = [];
  for (let cy = 0; cy < rows; cy++) {
    for (let cx = 0; cx < columns; cx++) {
      const rgba = new Uint8Array(STREAM_CHUNK * STREAM_CHUNK * 4);
      for (let y = 0; y < STREAM_CHUNK; y++) {
        const gy = cy * STREAM_CHUNK + y;
        if (gy >= heightPx) break;
        for (let x = 0; x < STREAM_CHUNK; x++) {
          const gx = cx * STREAM_CHUNK + x;
          if (gx >= widthPx) break;
          let colour: Rgba | null = upper ? null : map.colours[cx % map.colours.length]!;
          // A four-tile magenta roof covers the player at (28,10), proving
          // streamed upper chunks stay above entities after camera scrolling.
          if (upper && map.roof && gx >= 27 * TILE && gx < 31 * TILE && gy >= 9 * TILE && gy < 12 * TILE) {
            colour = ROOF_COLOUR;
          }
          if (colour) rgba.set(colour, (y * STREAM_CHUNK + x) * 4);
        }
      }
      chunks.push(rgba);
    }
  }
  return { chunks, columns, rows };
}

const entries: StreamEntry[] = [];
const layers = new Map<string, { ground: StreamedLayer; upper: StreamedLayer }>();
for (const map of maps) {
  const groundChunks = chunksFor(map, false);
  const upperChunks = chunksFor(map, true);
  const ground = encodeStreamedLayer(
    `fixture-${map.id}-ground`,
    groundChunks.chunks,
    groundChunks.columns,
    groundChunks.rows,
    { chunkPx: STREAM_CHUNK },
  );
  const upper = encodeStreamedLayer(
    `fixture-${map.id}-upper`,
    upperChunks.chunks,
    upperChunks.columns,
    upperChunks.rows,
    { chunkPx: STREAM_CHUNK },
  );
  entries.push(...ground.entries, ...upper.entries);
  layers.set(map.id, { ground: ground.layer, upper: upper.layer });
}

const manifest = pakManifest(entries);
for (const entry of entries) {
  const file = streamEntryFile(entry.key);
  const path = join(HERE, file);
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.blob);
}
writeFileSync(join(HERE, "pak.json"), JSON.stringify(manifest, null, 2) + "\n");

const player = new Uint8Array(TILE * TILE * 4);
for (let y = 0; y < TILE; y++) {
  for (let x = 0; x < TILE; x++) {
    const border = x === 0 || y === 0 || x === TILE - 1 || y === TILE - 1;
    player.set(border ? [28, 24, 40, 255] : PLAYER_COLOUR, (y * TILE + x) * 4);
  }
}
mkdirSync(join(HERE, "assets"), { recursive: true });
writeFileSync(join(HERE, "assets/player.png"), encodePNG(player, TILE, TILE));
writeFileSync(join(HERE, "images.json"), JSON.stringify({ "assets/player.png": { psm: 3 } }, null, 2) + "\n");

const streamSource = streamManifestSource(
  maps.map((map) => ({
    id: map.id,
    width: map.width,
    height: map.height,
    ground: layers.get(map.id)!.ground,
    upper: layers.get(map.id)!.upper,
  })),
  { chunkPx: STREAM_CHUNK },
);
const q = JSON.stringify;
const frames = `[${Array.from({ length: 4 }, () => q("assets/player.png")).join(", ")}]`;
writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/streamed/gen-assets.ts — do not edit.\n` +
    `import type { GameAssets } from "../../../src/ui/game-assets.ts";\n\n` +
    `export const GAME_ASSETS: GameAssets = {\n` +
    `  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0,\n` +
    `  world: {\n` +
    maps.map((map) => `    ${q(map.id)}: { w: ${map.width * TILE}, h: ${map.height * TILE} },`).join("\n") + `\n` +
    `  },\n` +
    `  order: ${JSON.stringify(maps.map((map) => map.id))},\n` +
    `  npcSrc: {},\n` +
    `  player: { idle: ${frames}, walkL: ${frames}, walkR: ${frames} },\n` +
    `  stream: ${streamSource},\n` +
    `  layers: {\n` +
    `    ground: { placement: "ground", mode: "streamed", variants: { sparse: { refs: { ${q(FIELD_ID)}: ${JSON.stringify(layers.get(FIELD_ID)!.upper.refs)} }, columns: { ${q(FIELD_ID)}: ${layers.get(FIELD_ID)!.upper.columns} }, chunkPx: ${STREAM_CHUNK} } } },\n` +
    `    upper: { placement: "upper", mode: "streamed", variants: {} },\n` +
    `    "extra-stream": { placement: "below", mode: "streamed", variants: { on: { refs: { ${q(FIELD_ID)}: ${JSON.stringify(layers.get(FIELD_ID)!.ground.refs)} }, columns: { ${q(FIELD_ID)}: ${layers.get(FIELD_ID)!.ground.columns} }, chunkPx: ${STREAM_CHUNK}, loadBudget: 1 } } },\n` +
    `  },\n` +
    `};\n`,
);

console.log(`streamed fixture: ${maps.length} maps, ${entries.length} TILESET entries, ${entries.reduce((n, e) => n + e.blob.length, 0)} bytes`);
