// tests/fixtures/world-bounded/gen-assets.ts — deterministic build-time
// cooking for the world-bounded fixture: each 4x4 map becomes one streamed
// ground TILESET entry (a single 256px chunk, solid colour) plus the player
// sprite. Reproducible byte for byte; the PNG/pkts outputs are build
// artifacts kept out of git.

import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { encodePNG } from "../../../vendor/pocketjs/tests/png.ts";
import {
  encodeStreamedLayer,
  pakManifest,
  streamEntryFile,
  streamManifestSource,
  type StreamEntry,
  type StreamedLayer,
} from "../../../tools/lib/stream.ts";
import {
  GROUND_COLOUR_BYTES,
  MAP_IDS,
  MAP_SIZE,
  WORLD_BOUNDED_PROJECT,
} from "./fixture-data.ts";

const HERE = import.meta.dir;
const TILE = 16;
const CHUNK = 256;

type Rgba = readonly [number, number, number, number];

function solidChunk(colour: Rgba): Uint8Array {
  const rgba = new Uint8Array(CHUNK * CHUNK * 4);
  for (let y = 0; y < MAP_SIZE * TILE; y++) {
    for (let x = 0; x < MAP_SIZE * TILE; x++) {
      rgba.set(colour, (y * CHUNK + x) * 4);
    }
  }
  return rgba;
}

// A translucent canopy across the top tile row of each map, in a colour
// derived from the map's ground. The upper band then loads real textures
// (a null-ref upper would leave the upper residency path unmeasured).
const UPPER_COLOURS: readonly Rgba[] = GROUND_COLOUR_BYTES.map(([r, g, b]) => [
  Math.min(255, r + 70),
  Math.min(255, g + 30),
  Math.min(255, b + 50),
  170,
]);

function canopyChunk(colour: Rgba): Uint8Array {
  const rgba = new Uint8Array(CHUNK * CHUNK * 4);
  for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < MAP_SIZE * TILE; x++) {
      rgba.set(colour, (y * CHUNK + x) * 4);
    }
  }
  return rgba;
}

const entries: StreamEntry[] = [];
const cooked = new Map<string, { ground: StreamedLayer; upper: StreamedLayer }>();
for (let i = 0; i < MAP_IDS.length; i++) {
  const id = MAP_IDS[i]!;
  const ground = encodeStreamedLayer(
    `world-${id}-ground`,
    [solidChunk(GROUND_COLOUR_BYTES[i]!)],
    1,
    1,
    { chunkPx: CHUNK },
  );
  // One upper chunk per map with a translucent canopy strip, so the upper
  // band loads and evicts real textures along the traversal.
  const upper = encodeStreamedLayer(
    `world-${id}-upper`,
    [canopyChunk(UPPER_COLOURS[i]!)],
    1,
    1,
    { chunkPx: CHUNK },
  );
  entries.push(...ground.entries, ...upper.entries);
  cooked.set(id, { ground: ground.layer, upper: upper.layer });
}

for (const entry of entries) {
  const path = join(HERE, streamEntryFile(entry.key));
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, entry.blob);
}
writeFileSync(join(HERE, "pak.json"), JSON.stringify(pakManifest(entries), null, 2) + "\n");

function solidSprite(colour: Rgba): Uint8Array {
  const rgba = new Uint8Array(TILE * TILE * 4);
  for (let y = 0; y < TILE; y++) {
    for (let x = 0; x < TILE; x++) {
      const edge = x === 0 || y === 0 || x === TILE - 1 || y === TILE - 1;
      rgba.set(edge ? [24, 18, 34, 255] : colour, (y * TILE + x) * 4);
    }
  }
  return rgba;
}

mkdirSync(join(HERE, "assets"), { recursive: true });
writeFileSync(join(HERE, "assets/player.png"), encodePNG(solidSprite([250, 244, 248, 255]), TILE, TILE));
writeFileSync(join(HERE, "images.json"), JSON.stringify({ "assets/player.png": { psm: 3 } }, null, 2) + "\n");
writeFileSync(join(HERE, "sprites.json"), JSON.stringify({}, null, 2) + "\n");

const stream = streamManifestSource(MAP_IDS.map((id) => ({
  id,
  width: MAP_SIZE,
  height: MAP_SIZE,
  ground: cooked.get(id)!.ground,
  upper: cooked.get(id)!.upper,
})), { chunkPx: CHUNK, margin: TILE });
const q = JSON.stringify;
const frames = `[${Array.from({ length: 4 }, () => q("assets/player.png")).join(", ")}]`;
const world = MAP_IDS.map((id) => `    ${q(id)}: { w: ${MAP_SIZE * TILE}, h: ${MAP_SIZE * TILE} },`).join("\n");
writeFileSync(
  join(HERE, "assets-game.ts"),
  `// AUTO-GENERATED by tests/fixtures/world-bounded/gen-assets.ts — do not edit.\n` +
    `import type { GameAssets } from "../../../src/ui/game-assets.ts";\n\n` +
    `export const GAME_ASSETS: GameAssets = {\n` +
    `  ground: {}, upper: {}, chunkColumns: {}, maxChunks: 0, maxActors: 4,\n` +
    `  world: {\n${world}\n  },\n` +
    `  order: ${JSON.stringify(MAP_IDS)},\n` +
    `  npcSrc: {},\n` +
    `  player: { idle: ${frames}, walkL: ${frames}, walkR: ${frames} },\n` +
    `  stream: ${stream},\n` +
    `};\n`,
);
console.log(
  `world-bounded fixture: ${MAP_IDS.length} maps, ${entries.length} TILESET entries, ` +
  `${entries.reduce((sum, entry) => sum + entry.blob.length, 0)} bytes`,
);
void WORLD_BOUNDED_PROJECT;
